# Generated by Django 2.2.9 on 2020-09-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20200925_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
    ]
