# Generated by Django 2.2.9 on 2020-09-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_auto_20200925_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/'),
        ),
    ]
