# Generated by Django 2.2.9 on 2020-09-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_auto_20200925_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='spots', to='spots.Category'),
        ),
    ]
