# Generated by Django 2.2.9 on 2020-09-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0007_auto_20200926_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotimage',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spots.Spot'),
        ),
    ]
